### PR TITLE
Update data.py

### PR DESCRIPTION
**Pull request by SonicDiscord**

### CODE REVIEW

**Comment by AstroOrbis** [comment]
Bro. You gotta be more careful w/ ur tokens. Close this and hope to god nobody checks this pr, otherwise your account is gonna get tokenf***ed.

**Comment by ARealWant** [comment]
Closing this due to it's leaking a Discord token, instead of doing a real change.

**Comment by 7Ahmad** [comment]
oof

**Comment by 7Ahmad** [comment]
:(

**Comment by AstroOrbis** [comment]
F

**Comment by 7Ahmad** [comment]
How do i use one if i found one

**Comment by AstroOrbis** [comment]
give it to me and i'll make sure it's valid and can be used I guess

**Comment by 7Ahmad** [comment]
Whats ur discord mine is 7Ahmad 3239

**Comment by AstroOrbis** [comment]
AstroOrbis#0623

**Pull request closed without merging**
